[versions]
paper = "1.21.5-R0.1-SNAPSHOT"

boostedyaml = "1.3.6"

shadow = "9.3.0"
pluginyml = "0.8.0"

server = "4.0.2"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

boostedYaml = { group = "dev.dejvokep", name = "boosted-yaml", version.ref = "boostedyaml" }

[plugins]
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadow" }
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginyml" }

server = { id = "dev.s7a.gradle.minecraft.server", version.ref = "server" }