[versions]
paper = "1.21.5-R0.1-SNAPSHOT"
smartinv = "1.2.7"

boostedyaml = "1.3.6"

shadow = "9.3.0"
pluginyml = "0.8.0"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
smartInvs = { group = "fr.minuskube.inv", name = "smart-invs", version.ref = "smartinv" }

boostedYaml = { group = "dev.dejvokep", name = "boosted-yaml", version.ref = "boostedyaml" }

[plugins]
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadow" }
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginyml" }